site_name: ESP 21.2.0

theme:
  name: 'material'

site_author: 'Namiral'
site_url: ''
remote_branch: gh-pages
# Repository
repo_name: 'ESP-DOC'
repo_url: https://github.com/namirialgroup/esp-docs
edit_uri: tree/main/docs/

# markdown_extensions:
#   - codehilite
#   - pymdownx.superfences
#   - admonition
markdown_extensions:
  - mdx_truly_sane_lists

nav:
  - Overview: index.md
  - Getting started: configuration.md
  - Integration scenarios:
    - Get key: integrations/getkey.md
    - Perform a login: integrations/login.md
    - Get user token: integrations/token.md    
  #   - Credentials: integration/credential.md
  #   - Get user detail: integration/user.md
  #   - Handle security information: integration/security.md
  #   - Multi Factor Authentication: integration/mfa.md
  - Changelog : changelog.md
  # - Previous versions: ../
  - API Reference : apis.html
    
